# Generated by Django 3.0.6 on 2021-10-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('nome', models.CharField(max_length=250)),
                ('codigo', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
