# Generated by Django 3.0.6 on 2021-10-20 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaAL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('nome', models.CharField(max_length=250)),
                ('codigo', models.CharField(max_length=30)),
                ('mae', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children_set', to='empresa.EmpresaAL')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
