# Generated by Django 3.0.6 on 2021-10-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_empresaal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresaal',
            old_name='mae',
            new_name='parent',
        ),
    ]
